### ISSUE TITLE
Filename cannot be empty error

### ISSUE THREAD

**Issue by newfolders** [mgp25/Instagram-API#1001]
Hi. I'm getting this error. I'm using database. I don't understand this.
```

( ! ) Warning: file_put_contents(): Filename cannot be empty in C:\wamp\www\instanew\vendor\mgp25\instagram-php\src\http\HttpInterface.php on line 55
Call Stack
#	Time	Memory	Function	Location
1	0.0006	139056	{main}( )	...\search.php:0
2	0.0302	967760	InstagramAPI\Instagram->login( )	...\search.php:41
3	0.0302	967856	InstagramAPI\Instagram->timelineFeed( )	...\Instagram.php:175
4	0.0311	991808	InstagramAPI\Request->getResponse( )	...\Instagram.php:272
5	0.0311	992688	InstagramAPI\HttpInterface->request( )	...\Instagram.php:1845
6	43.8422	994512	file_put_contents ( )	...\HttpInterface.php:55
```

**Comment by mgp25** [comment]
@newfolders i dont recommend you using master branch at the moment, use stable releases instead.

**Comment by newfolders** [comment]
I'm using stable release.

**Comment by newfolders** [comment]
Everything was working great. I changed nothing but suddenly this error appears. And datas in the cookies column of user_settings table is filling with blank (null maybe).

**Comment by jpmoney5065** [comment]
Same issue I was having with the curl lib update  (haven't tested out the guzzle update yet)
@newfolders maybe your composer updated?
@mgp25  maybe make a branch for testing the new httpinterface/guzzle then merge back when stable? Otherwise I feel you will keep getting this complaint.

**Comment by newfolders** [comment]
@jpmoney5065 how can I check if my composer updated it?

composer.lock file has this
"name": "mgp25/instagram-php",
            "version": "v1.6.1",

**Comment by newfolders** [comment]
Is there any chance of Curl got mixed up with my twitter api? Some thing related to cookies or something. I don't know.

**Comment by jpmoney5065** [comment]
Just check your `http/httpinterface.php` file

The http class should start like:
```
namespace InstagramAPI;
class HttpInterface
{    
    protected $parent;
    protected $userAgent;
    protected $verifyPeer = false;
    protected $verifyHost = false;
    public $proxy = [];
```


And NOT like this: 
```
namespace InstagramAPI;
use GuzzleHttp\Client;
use GuzzleHttp\Cookie\CookieJar;
use GuzzleHttp\Cookie\FileCookieJar;
class HttpInterface
{
    protected $parent;
    protected $userAgent;
    protected $verifyPeer = true;
    protected $verifyHost = 2;
    public $proxy = [];
    public $outputInterface;
```

**Comment by newfolders** [comment]
@jpmoney5065 

Starts like this :(

```
<?php

namespace InstagramAPI;

class HttpInterface
{
    protected $parent;
    protected $userAgent;
    protected $verifyPeer = false;
    protected $verifyHost = false;
    public $proxy = [];
```

**Comment by jpmoney5065** [comment]
Strange we are having the exact same issue if you are all the way back at 1.6 Stable.

Code from commit 53a0c4a8adad967ab1a996364cafa81a61cf2d5a is working for me.

**Comment by newfolders** [comment]
tempnam(sys_get_temp_dir(), uniqid('_instagram_cookie'));

My temp directory broken maybe?

**Comment by newfolders** [comment]
Before removing c:/windows/temp files, I changed php version on wamp, restarted services. Even I restarted my pc. Nothing of these worked.

**Comment by newfolders** [comment]
Before removing c:/windows/temp files, I changed php version on wamp, restarted services. Even I restarted my pc. Non of these worked.

**Comment by frrakn** [comment]
@mgp25 maybe it makes sense to just tag a commit as "kind of stable". I think most users want to be able to use a very recent version (1.6 is app version 10.3.2, which will have issues with IG occasionally prompting the user to upgrade to the newest version, 10.10).

@newfolders I got the same issue, I suggest using @jpmoney5065's solution and using a more stable version in the meantime. You can do this by using ```dev-master#53a0c4a8adad967ab1a996364cafa81a61cf2d5a``` in `composer.json`.

**Comment by SteveJobzniak** [comment]
@frrakn Master is not "stable". It's the HEAD of the latest commits. Only the tagged releases are verified.

Anyway, both me and mgp25 are working very hard all day on v2.0 of this library, which rewrites _everything_ to use Guzzle and exceptions instead of the old, slow, archaic PHP-cURL system. These changes will not be fully backwards compatible. But on the plus side the library will be much, much faster than the old API! Something like 3x faster per request() call.

The request() function is nearly done now, and problems you mentioned such as not saving cookies are fixed now (we hadn't finished the cookie writing in the test code you guys used). But lots more work remains to be done in HttpInterface in other functions. Only request(), the most important function, is rewritten so far.

For those curious how migration will to 2.0 will work:

- We will provide a migration document with instructions for adapting your projects.
- You'll be losing all of your old cookies from 1.x of the library (no way around that, sorry, Guzzle itself uses a brand new cookie storage format).
- Various old functions are removed and changed to Guzzle methods instead. So far just the functions for setting SSL validation, and for setting the proxy.
- Exceptions will be thrown by all API functions in case there's an error. That way you never have to constantly check the return-value of every API function anymore. You just write clean `try{}catch{}` blocks around your API calls, to handle errors at any code level you want to. You can then do all of your work in a single block, or separate the work into smaller parts and validate each step, so that unimportant failures in less important sub-steps don't trigger the main exception handler. It's all up to you. And it will be way better than the old system. This is the right way to handle errors.

@newfolders Don't worry about write-access to that folder. The next version of the library does not use `sys_get_temp_dir()` for mysql cookies. It now uses cookies stored in RAM/the database instead of putting them in a temp file on disk. Only actual filecookiejars (the default if no custom SettingsAdapter is provided) still use cookie files on disk.

**Comment by frrakn** [comment]
@SteveJobzniak I contribute too, and I never meant master must be stable. I meant that there should be a commit thats tagged as "stable enough" that's more recent. `master` is too unstable to consistently use and expect to generally work, but `1.6` is starting to get a little too old.

**Comment by jpmoney5065** [comment]
@SteveJobzniak @mgp25  Awesome to see so much working being put into this!

Any chance of an option to pass in a PDO connection for the settings instead of doubling up on connections?

**Comment by SteveJobzniak** [comment]
@frrakn Ah yes, you're right, the latest tag is two months old. Well, after 2.x we'll think of something. Either pushing release tags more frequently. Or doing work-in-progress development in a separate branch.

@jpmoney5065 I don't know. We're mainly reworking the HTTP layer and have tons of work to do already relating to that. But if you come up with a nice patch for PDO connection reuse, we'll merge it! :)

**Comment by newfolders** [comment]
@SteveJobzniak My error is back. I got more than 65.000 files. Starts _in1A0A.tmp ends _inFFFF.tmp. The FFFF makes me think. Maybe no more file name?

**Comment by SteveJobzniak** [comment]
@newfolders Yes that seems to be it. Because the old code is terrible. It generates a random temp filename using PHP's function, dumps all cookies into the file (from memory), then reads that file back into memory. Which is silly enough. But to make matters worse it never deletes the temp file on disk.

The ongoing Guzzle rewrite doesn't use such silly code at all. No temp files!

**Comment by newfolders** [comment]
Got it!

http://php.net/manual/en/function.tempnam.php

Note: If PHP cannot create a file in the specified dir parameter, it falls back on the system default. On NTFS this also happens if the specified dir contains more than 65534 files.

How can I fix this now?

**Comment by SteveJobzniak** [comment]
@newfolders You'd have to edit HttpInterface.php manually. In all locations where it generates temp names. Make it save the temp name to some variable and delete it after each request.

**Comment by newfolders** [comment]
@SteveJobzniak Should I put unlink at the end of "function request" like this?

unlink($cookieJarFile);

**Comment by joseflorido** [comment]
This happened to me and system ran out of inodes. An easy fix is to switch
settingsAdapter to mysql type and this way cookies are not saved on tmp
file. Otherwise you could make /tmp a tmpfs partition and remove older
files every few minutes to keep them in control

**Comment by newfolders** [comment]
@joseflorido I'm using mysql type. This is about temp files.

**Comment by newfolders** [comment]
@SteveJobzniak I put it like this. Is it ok?

```
if ($this->parent->settingsAdopter['type'] == 'mysql') {
            $newCookies = file_get_contents($cookieJarFile);
            $this->parent->settings->set('cookies', $newCookies);
 }
unlink($cookieJarFile);
```

**Comment by newfolders** [comment]
Looks like that code solved problem. Also it is windows php limitations, it won't save data like this: _instagram_cookie58b8d9e52230e. It saves it like _in53E7.tmp. _in instead of _instagram_cookie.

**Comment by SteveJobzniak** [comment]
@joseflorido The MySQL adapter is *the one* that uses temp filenames in the old insane code! ;-) The only one which doesn't create temp files is the basic filecookiejar method where a single, permanent disk-filename is provided.

@newfolders Yes that workaround will work properly. The old code always creates brand new cURL handles every request(), so the old cookie file doesn't matter and can be deleted afterwards.
