### ISSUE TITLE
FFmpeg and FFprobe

### ISSUE THREAD

**Issue by rudemex** [mgp25/Instagram-API#1267]
Hello, I have installed FFmpeg and FFprobe but it still returns error.
I run a video terminal and return the information without problem.

`ffprobe -v quiet -print_format json -show_format -show_streams /Users/mex/Sitios/arduino/ArduinoProjects/ws-woonkybot/development/deploy/assets/images/captures/IMG_4404.mp4 `

`{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1001/60000",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 720,
            "height": 1280,
            "coded_width": 720,
            "coded_height": 1280,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "9:16",
            "pix_fmt": "yuv420p",
            "level": 31,
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "30000/1001",
            "avg_frame_rate": "30000/1001",
            "time_base": "1/30000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 453480,
            "duration": "15.116000",
            "bit_rate": "3366805",
            "bits_per_raw_sample": "8",
            "nb_frames": "453",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "und",
                "handler_name": "VideoHandler"
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/44100",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "44100",
            "channels": 1,
            "channel_layout": "mono",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/44100",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 667630,
            "duration": "15.139002",
            "bit_rate": "192000",
            "max_bit_rate": "192000",
            "nb_frames": "654",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "und",
                "handler_name": "SoundHandler"
            }
        }
    ],
    "format": {
        "filename": "/Users/mex/Sitios/arduino/ArduinoProjects/ws-woonkybot/development/deploy/assets/images/captures/IMG_4404.mp4",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
        "format_long_name": "QuickTime / MOV",
        "start_time": "0.000000",
        "duration": "15.186000",
        "size": "6743092",
        "bit_rate": "3552267",
        "probe_score": 100,
        "tags": {
            "major_brand": "isom",
            "minor_version": "512",
            "compatible_brands": "isomiso2avc1mp41",
            "encoder": "Lavf57.25.100"
        }
    }
}
`

ffmpeg version
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers

ffprobe version
ffprobe version 3.2.4 Copyright (c) 2007-2017 the FFmpeg developers

Any idea that it may be going wrong?

thanks!

pd: sorry, my english is not very good.

**Comment by mgp25** [comment]
Related/Duplicated: https://github.com/mgp25/Instagram-API/issues/1264

**Comment by Triden** [comment]
You can rewrite the code slightly and do not use FFprobe at all. For example, you can see how it works in version 1.6

**Comment by SteveJobzniak** [comment]
@Triden No, you cannot rewrite the code if you want working video uploads. We validate/fix the video and thumbnail data so that Instagram will accept the video/thumbnail.

@rudemex Your ffprobe and ffmpeg must be callable by PHP, which uses "ffprobe" and "ffmpeg" as commands. So it must be in your Environment PATH, or the binaries must be in the same folder as your script's "working directory". So that it finds them.

This is not related to API. Your system needs fixing. You can make a test script:

```php
<?php
shell_exec('ffprobe');
shell_exec('ffmpeg');
?>
```

When both of those work, you have fixed your PHP installation.

**Comment by Triden** [comment]
@SteveJobzniak. My experiments showed that if I change the thumbnail of the video to the desired format. Any mp4 video is loaded. You did not check?

**Comment by rudemex** [comment]
It's a great job that they did with this library, but just an opinion, there should be another alternative to upload the videos without ffmpeg and ffprobe, since most of the servers do not have this.

If I find this solution, I will notify you, and it is in you if you want to include it or not, anyway, thank you very much for the help.

regards

pd: sorry again, my english is not very good.

**Comment by SteveJobzniak** [comment]
Instagram has aspect ratio, resolution and length limits on videos. Which we must follow.

@rudemex Even on a server where you cannot install packages, you can put ffmpeg and ffprobe binaries in the CWD (working dir) of the PHP script.

There is a PHP library called getid3.org but it's unacceptable because of tons of bugs with reading video metadata (see its bug forum), not very maintained code, and it requires half of PHP's "max memory" to read MP4 files (the most popular format).

But rudemex, you should be able to solve this easily on your server by placing pre-built ffmpeg/ffprobe linux binaries next to your PHP script and then they would be found. Please check if that works.

**Comment by SteveJobzniak** [comment]
@rudemex I've fixed the issue.

Look at this commit: https://github.com/mgp25/Instagram-API/commit/f323144bb3b2384d1911444a36d0d95f317f22ee

All you have to do:

1. Download ffmpeg+ffprobe binaries for linux.
2. Unzip them on your server somewhere.
3. Use the method described in that commit, to set the FULL paths to your ffmpeg and ffprobe binaries.

It's good that we've fixed this since most servers don't allow users to install packages globally. This new solution works if your server allows binary file execution, and most allow that!

Enjoy!

**Comment by rudemex** [comment]
hi @SteveJobzniak 
I was able to upload videos like this: 

1- follow this tutorial to download the ffprobe & ffmpeg: http://ericholsinger.com/install-ffmpeg-on-a-mac
2- in the file utils.php, i edited the lines that execute the function ffmpeg & ffprobe, exchanging the path with the one from step 1


So with these minor changes, I could upload the videos. Of course, I'm still having problems with Instagram size & duration, and this time I also found a different bug `"error_description":"Undefined variable: res"`

After searching through all the library files,  i found this variable in debug.php
I haven't had the chance to look further into this, but i believe that if you declare the variable as null you'll be able to fix it. 

I'll keep you posted !

**Comment by mgp25** [comment]
Im using a mac, with current code works perfectly, even previous versions

**Comment by rudemex** [comment]
Hi @mgp25 I am using the latest version.
I'm following the problem #1285 with @SteveJobzniak jajajja

Later I'll start to check some things, to see if I can make my solution work when uploded to a standard server.

Regrads!

**Comment by SteveJobzniak** [comment]
@rudemex 
1. `"error_description":"Undefined variable: res"` is not an error from our code. It may be from instagram. And your idea of src/Debug.php is wrong. Our `$res` there is always defined.

2. I literally told you how to fix the ffmpeg/ffprobe issue in the new commit text. Scroll up and read my message and the commit text and you will see what to do... :)
.

**Comment by rudemex** [comment]
@SteveJobzniak I got to check your comment, and also I saw the library update you've made. It solves it like my solution, but yours does it in a tidier way. I'm now uploading the binary files to a standard server in order to check whether it works properly. 
About the $res, you're right, I didn't read thoroughly - it was kinda late when I read it tbh-
I'll keep looking into it so I can get it to work.
Thanks

**Comment by rudemex** [comment]
I am writing to tell you that you have already solved the problem of uploading videos. It has many laps the subject of the videos hahaha but it works. I still did not solve the error of the variable $ res. Anything new will let them know.

From now many thanks and greetings.
Pd: just pay off some debts make a donation to your work!

**Comment by SteveJobzniak** [comment]
@rudemex Thanks for informing us about your success :) I actually think "res" is a different error coming from Instagram server.

**Comment by rudemex** [comment]
@SteveJobzniak @mgp25 In fact, I just found the variable res, it is one of my variables that was not defined and returned in a json as empty, therefore, your project is working perfectly! What if, I will investigate some way to work with the videos, create some function to adjust them, since it is quite complicated if you do not work with video editors. Anything new will be made known! Greetings.
